all: compilar enlazar

compilar:
	g++ -c main.cpp algoritmoGenetico.cpp cromosoma.cpp  random_generator.cpp

enlazar:
	g++ -o vendedorViajero main.o algoritmoGenetico.o cromosoma.o  random_generator.o